apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: helloservice
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - helloservice.podtatohead-hardening.127.0.0.1.nip.io
  - helloservice
  http:
  - route:
    - destination:
        host: helloservice-canary.podtatohead-hardening.svc.cluster.local
      weight: 100
    - destination:
        host: helloservice-primary.podtatohead-hardening.svc.cluster.local
